version: '3.7'
services:

  database:
    image: postgres:12.2-alpine
    networks:
      - hostnet
    volumes:
      - /var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=localeat
      - POSTGRES_PASSWORD=localeat
      - PGDATA=/var/lib/postgresql/data/pgdata

  core:
    build:
      context: "."
      dockerfile: ./core/Dockerfile
    image: benjaminpochat/localeat-core:${DOCKER_IMAGE_TAG:-latest}
    networks:
      - hostnet
    depends_on:
      - database
    environment:
      - localeat_datasource_url=jdbc:postgresql://localhost:5432/localeat
      - localeat_datasource_username=localeat
      - localeat_datasource_password=localeat

  ui:
    build:
      context: "."
      dockerfile: ./ui/Dockerfile
    image: benjaminpochat/localeat-ui:${DOCKER_IMAGE_TAG:-latest}
    networks:
      - hostnet
    depends_on:
      - core

networks:
  hostnet:
    external: true
    name: host


