version: '3.7'
services:

  database:
    image: postgres:12.2-alpine
    volumes:
      - ${postgres_datafile_path}:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=localeat
      - POSTGRES_PASSWORD=${postgres_password}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${postgres_port}:5432

  core:
    image: benjaminpochat/localeat-core:${DOCKER_IMAGE_TAG:-latest}
    depends_on:
      - database
    environment:
      - spring_datasource_url=jdbc:postgresql://database:5432/localeat
      - spring_datasource_username=localeat
      - spring_datasource_password=${postgres_password}
      - spring_jpa_properties_hibernate_dialect=org.hibernate.dialect.PostgresPlusDialect
      - localeat_smtp_username=la.viande.en.direct@gmail.com
      - localeat_smtp_password=${smtp_password}
      - localeat_http_domainname=${domain_name}
      - localeat_payment_molliepaymentapikey=${mollie_api_key}
    ports:
      - ${backend_port}:8080

  ui:
    image: benjaminpochat/localeat-ui:${DOCKER_IMAGE_TAG:-latest}
    depends_on:
      - core
    volumes:
      - ${frontend_config_file_path}:/usr/local/apache2/htdocs/assets/config
    ports:
      - ${frontend_port}:80
