version: '3.7'
services:

  core:
    build:
      context: "."
      dockerfile: ./core/Dockerfile
    image: benjaminpochat/localeat-core:${DOCKER_IMAGE_TAG:-latest}

  ui:
    build:
      context: "."
      dockerfile: ./ui/Dockerfile
      args:
        - localeat_environment_type=production
    image: benjaminpochat/localeat-ui:${DOCKER_IMAGE_TAG:-latest}
