version: '3.7'
services:

  database:
    image: postgres:12.2-alpine
    volumes:
      - <path_to_postgres_datafile_folder_on_real_server>:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=localeat
      - POSTGRES_PASSWORD=<password>
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - <published_postgres_port>:5432

  core:
    image: benjaminpochat/localeat-core:${DOCKER_IMAGE_TAG:-latest}
    depends_on:
      - database
    environment:
      - spring_datasource_url=jdbc:postgresql://database:5432/localeat
      - spring_datasource_username=localeat
      - spring_datasource_password=<password>
      - spring_jpa_properties_hibernate_dialect=org.hibernate.dialect.PostgresPlusDialect
      - localeat_smtp_username=la.viande.en.direct@gmail.com
      - localeat_smtp_password=localeat
      - localeat_http_domainname=<domain_name_for_localeat_server>
      - localeat.payment.molliepaymentapikey=<mollie_api_key>
    ports:
      - <published_backend_port>:8080

  ui:
    image: benjaminpochat/localeat-ui:${DOCKER_IMAGE_TAG:-latest}
    depends_on:
      - core
    volumes:
      - <path_to_folder_containing_localeat_ui_config_file_on_real_server>:/usr/local/apache2/htdocs/assets/config
    ports:
      - <published_frontend_port>:80
