version: '3.7'
services:

  database:
    image: postgres:12.2-alpine
    networks:
      - hostnet
    environment:
      - POSTGRES_USER=localeat
      - POSTGRES_PASSWORD=localeat
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  core:
    build:
      context: "."
      dockerfile: ./core/Dockerfile
    image: benjaminpochat/localeat-core:${DOCKER_IMAGE_TAG:-latest}
    networks:
      - hostnet
    depends_on:
      - database
    environment:
      - localeat_datasource_url=jdbc:postgresql://localhost:5432/localeat
      - localeat_datasource_username=localeat
      - localeat_datasource_password=localeat
      - localeat_smtp_username=la.viande.en.direct@gmail.com
      - localeat_smtp_password=localeat
      - localeat_http_domainname=http://localhost:4200
    ports:
      - 8080:8080

  ui:
    build:
      context: "."
      dockerfile: ./ui/Dockerfile
      args:
        - localeat_environment_type=production
    image: benjaminpochat/localeat-ui:${DOCKER_IMAGE_TAG:-latest}
    networks:
      - hostnet
    depends_on:
      - core
    volumes:
      - /home/benjamin/Documents/workspace/localeat/test/localeat-ui-config:/usr/local/apache2/htdocs/assets/config
    ports:
      - 80:80

networks:
  hostnet:
    external: true
    name: host